---

- name: "Apply EKS ADMIN service account to EKS Cluster"
  hosts: localhost
  tasks:
    - name: "Render YAML"
      template:
        src: templates/eks_admin_service_account.yaml.j2
        dest: /tmp/eks_admin.yaml
    
    - name: "APPLY YAML"
      command: "kubectl apply -f /tmp/eks_admin.yaml"
      register: result

    - name: "Show outputs"
      debug:
        msg: "{{ result.stdout_lines }}"

    