---

- name: Install Metrics Server on EKS Cluster
  hosts: localhost

  tasks:
    - name: "Download Metrics Server and apply to cluster"
      shell: |
        DOWNLOAD_URL=$(curl -Ls "https://api.github.com/repos/kubernetes-sigs/metrics-server/releases/latest" | jq -r .tarball_url)
        DOWNLOAD_VERSION=$(grep -o '[^/v]*$' <<< $DOWNLOAD_URL)
        curl -Ls $DOWNLOAD_URL -o metrics-server-$DOWNLOAD_VERSION.tar.gz
        mkdir metrics-server-$DOWNLOAD_VERSION
        tar -xzf metrics-server-$DOWNLOAD_VERSION.tar.gz --directory metrics-server-$DOWNLOAD_VERSION --strip-components 1
        kubectl apply -f metrics-server-$DOWNLOAD_VERSION/deploy/1.8+/
        rm -rf metrics-server-$DOWNLOAD_VERSION metrics-server-$DOWNLOAD_VERSION.tar.gz

      register: "output"


    - name: "Show outputs"
      debug: msg="{{ output.stdout_lines }}"